In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("/home/ubontu/Downloads/health care project/uber project/archive/NYC.csv")
df = df[df['passenger_count'] > 0]

In [5]:
df.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435

In [6]:
df = df.drop(columns=["id","vendor_id","passenger_count","store_and_fwd_flag","dropoff_datetime"])

In [7]:
df

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration
0,2016-03-14 17:24:55,-73.982155,40.767937,-73.964630,40.765602,455
1,2016-06-12 00:43:35,-73.980415,40.738564,-73.999481,40.731152,663
2,2016-01-19 11:35:24,-73.979027,40.763939,-74.005333,40.710087,2124
3,2016-04-06 19:32:31,-74.010040,40.719971,-74.012268,40.706718,429
4,2016-03-26 13:30:55,-73.973053,40.793209,-73.972923,40.782520,435
...,...,...,...,...,...,...
1458639,2016-04-08 13:31:04,-73.982201,40.745522,-73.994911,40.740170,778
1458640,2016-01-10 07:35:15,-74.000946,40.747379,-73.970184,40.796547,655
1458641,2016-04-22 06:57:41,-73.959129,40.768799,-74.004433,40.707371,764
1458642,2016-01-05 15:56:26,-73.982079,40.749062,-73.974632,40.757107,373
1458643,2016-04-05 14:44:25,-73.979538,40.781750,-73.972809,40.790585,198

In [8]:
df["pickup_longitude"].dtype

dtype('float64')

In [9]:
pick_up_factor = df
pick_up_factor["pickup_datetime"] =pd.to_datetime(pick_up_factor["pickup_datetime"])

In [10]:
pick_up_factor

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration
0,2016-03-14 17:24:55,-73.982155,40.767937,-73.964630,40.765602,455
1,2016-06-12 00:43:35,-73.980415,40.738564,-73.999481,40.731152,663
2,2016-01-19 11:35:24,-73.979027,40.763939,-74.005333,40.710087,2124
3,2016-04-06 19:32:31,-74.010040,40.719971,-74.012268,40.706718,429
4,2016-03-26 13:30:55,-73.973053,40.793209,-73.972923,40.782520,435
...,...,...,...,...,...,...
1458639,2016-04-08 13:31:04,-73.982201,40.745522,-73.994911,40.740170,778
1458640,2016-01-10 07:35:15,-74.000946,40.747379,-73.970184,40.796547,655
1458641,2016-04-22 06:57:41,-73.959129,40.768799,-74.004433,40.707371,764
1458642,2016-01-05 15:56:26,-73.982079,40.749062,-73.974632,40.757107,373
1458643,2016-04-05 14:44:25,-73.979538,40.781750,-73.972809,40.790585,198

In [11]:
import datetime as dt
df["pickup_date"] = df["pickup_datetime"].dt.day
df["pickup_month"] = df["pickup_datetime"].dt.month
df["pickup_hour"] =  df["pickup_datetime"].dt.hour
df["pickup_minute"] =  df["pickup_datetime"].dt.minute
df["pickup_dayofweek"] = df["pickup_datetime"].dt.dayofweek
# df["pickup_second"] =  df["pickup_datetime"].dt.second

In [12]:
df = df[(df['pickup_longitude'] <= -73.75) & (df['pickup_longitude'] >= -74.03)]
df = df[(df['pickup_latitude'] <= 40.85) & (df['pickup_latitude'] >= 40.63)]
df = df[(df['dropoff_longitude'] <= -73.75) & (df['dropoff_longitude'] >= -74.03)]
df = df[(df['dropoff_latitude'] <= 40.85) & (df['dropoff_latitude'] >= 40.63)]

In [13]:
df

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek
0,2016-03-14 17:24:55,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0
1,2016-06-12 00:43:35,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6
2,2016-01-19 11:35:24,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1
3,2016-04-06 19:32:31,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2
4,2016-03-26 13:30:55,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5
...,...,...,...,...,...,...,...,...,...,...,...
1458639,2016-04-08 13:31:04,-73.982201,40.745522,-73.994911,40.740170,778,8,4,13,31,4
1458640,2016-01-10 07:35:15,-74.000946,40.747379,-73.970184,40.796547,655,10,1,7,35,6
1458641,2016-04-22 06:57:41,-73.959129,40.768799,-74.004433,40.707371,764,22,4,6,57,4
1458642,2016-01-05 15:56:26,-73.982079,40.749062,-73.974632,40.757107,373,5,1,15,56,1
1458643,2016-04-05 14:44:25,-73.979538,40.781750,-73.972809,40.790585,198,5,4,14,44,1

In [14]:
df = pd.DataFrame(df)
df

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek
0,2016-03-14 17:24:55,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0
1,2016-06-12 00:43:35,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6
2,2016-01-19 11:35:24,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1
3,2016-04-06 19:32:31,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2
4,2016-03-26 13:30:55,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5
...,...,...,...,...,...,...,...,...,...,...,...
1458639,2016-04-08 13:31:04,-73.982201,40.745522,-73.994911,40.740170,778,8,4,13,31,4
1458640,2016-01-10 07:35:15,-74.000946,40.747379,-73.970184,40.796547,655,10,1,7,35,6
1458641,2016-04-22 06:57:41,-73.959129,40.768799,-74.004433,40.707371,764,22,4,6,57,4
1458642,2016-01-05 15:56:26,-73.982079,40.749062,-73.974632,40.757107,373,5,1,15,56,1
1458643,2016-04-05 14:44:25,-73.979538,40.781750,-73.972809,40.790585,198,5,4,14,44,1

In [15]:
df = df.drop(columns=["pickup_datetime"])

In [16]:

df = df[(df["trip_duration"] >= 60) & (df["trip_duration"] <= 7200)]

In [17]:
df

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek
0,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0
1,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6
2,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1
3,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2
4,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5
...,...,...,...,...,...,...,...,...,...,...
1458639,-73.982201,40.745522,-73.994911,40.740170,778,8,4,13,31,4
1458640,-74.000946,40.747379,-73.970184,40.796547,655,10,1,7,35,6
1458641,-73.959129,40.768799,-74.004433,40.707371,764,22,4,6,57,4
1458642,-73.982079,40.749062,-73.974632,40.757107,373,5,1,15,56,1
1458643,-73.979538,40.781750,-73.972809,40.790585,198,5,4,14,44,1

In [18]:

df.head()

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek
0,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0
1,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6
2,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1
3,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2
4,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5

In [19]:
from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    r = 6371 # km
    return c * r

df['trip_distance'] = df.apply(lambda x: haversine(x['pickup_longitude'], x['pickup_latitude'],
                                                     x['dropoff_longitude'], x['dropoff_latitude']), axis=1)

In [20]:

df = df[(df["trip_distance"] > 0) & (df["trip_distance"] <= 50)]

In [21]:
def manhattan_distance(lat1, lon1, lat2, lon2):
    a = haversine(lat1, lon1, lat1, lon2)
    b = haversine(lat1, lon1, lat2, lon1)
    return a + b

df['manhattan_distance'] = df.apply(lambda x: manhattan_distance(x['pickup_latitude'], x['pickup_longitude'], 
                                                                 x['dropoff_latitude'], x['dropoff_longitude']), axis=1)

In [22]:
df

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek,trip_distance,manhattan_distance
0,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0,1.498521,2.020292
1,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6,1.805507,2.347470
2,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1,6.385098,4.577756
3,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2,1.485498,0.653645
4,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5,1.188588,0.342565
...,...,...,...,...,...,...,...,...,...,...,...,...
1458639,-73.982201,40.745522,-73.994911,40.740170,778,8,4,13,31,4,1.225080,1.577565
1458640,-74.000946,40.747379,-73.970184,40.796547,655,10,1,7,35,6,6.049836,4.927422
1458641,-73.959129,40.768799,-74.004433,40.707371,764,22,4,6,57,4,7.824606,6.924923
1458642,-73.982079,40.749062,-73.974632,40.757107,373,5,1,15,56,1,1.092564,1.074840
1458643,-73.979538,40.781750,-73.972809,40.790585,198,5,4,14,44,1,1.134042,1.019365

In [23]:
df["trip_distance"].describe()

count    1.424953e+06
mean     3.319512e+00
std      3.665192e+00
min      4.241750e-04
25%      1.242253e+00
50%      2.086023e+00
75%      3.791256e+00
max      2.719163e+01
Name: trip_distance, dtype: float64

In [24]:
df            #################################

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek,trip_distance,manhattan_distance
0,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0,1.498521,2.020292
1,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6,1.805507,2.347470
2,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1,6.385098,4.577756
3,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2,1.485498,0.653645
4,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5,1.188588,0.342565
...,...,...,...,...,...,...,...,...,...,...,...,...
1458639,-73.982201,40.745522,-73.994911,40.740170,778,8,4,13,31,4,1.225080,1.577565
1458640,-74.000946,40.747379,-73.970184,40.796547,655,10,1,7,35,6,6.049836,4.927422
1458641,-73.959129,40.768799,-74.004433,40.707371,764,22,4,6,57,4,7.824606,6.924923
1458642,-73.982079,40.749062,-73.974632,40.757107,373,5,1,15,56,1,1.092564,1.074840
1458643,-73.979538,40.781750,-73.972809,40.790585,198,5,4,14,44,1,1.134042,1.019365

In [25]:
df['speed_mph'] = df['trip_distance'] / (df["trip_duration"] / 3600)
df = df[(df['speed_mph'] >= 2) & (df['speed_mph'] <= 60)]
df = df.drop(columns=['speed_mph'])

In [26]:
df

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek,trip_distance,manhattan_distance
0,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0,1.498521,2.020292
1,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6,1.805507,2.347470
2,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1,6.385098,4.577756
3,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2,1.485498,0.653645
4,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5,1.188588,0.342565
...,...,...,...,...,...,...,...,...,...,...,...,...
1458639,-73.982201,40.745522,-73.994911,40.740170,778,8,4,13,31,4,1.225080,1.577565
1458640,-74.000946,40.747379,-73.970184,40.796547,655,10,1,7,35,6,6.049836,4.927422
1458641,-73.959129,40.768799,-74.004433,40.707371,764,22,4,6,57,4,7.824606,6.924923
1458642,-73.982079,40.749062,-73.974632,40.757107,373,5,1,15,56,1,1.092564,1.074840
1458643,-73.979538,40.781750,-73.972809,40.790585,198,5,4,14,44,1,1.134042,1.019365

In [27]:
from sklearn.cluster import MiniBatchKMeans 
# import joblib
coords = np.vstack((df[['pickup_latitude', 'pickup_longitude']].values,
                    df[['dropoff_latitude', 'dropoff_longitude']].values))

kmeans = MiniBatchKMeans(n_clusters=20, batch_size=10000, random_state=42).fit(coords)
df['pickup_cluster'] = kmeans.predict(df[['pickup_latitude', 'pickup_longitude']])
df['dropoff_cluster'] = kmeans.predict(df[['dropoff_latitude', 'dropoff_longitude']])

# এখন Lat/Lon মুছে ফেলা যায়
# df = df.drop(columns=["pickup_longitude", "pickup_latitude", "dropoff_longitude", "dropoff_latitude"])
# joblib.dump(kmeans, "kmeans_model.pkl")

/home/ubontu/.local/lib/python3.13/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but MiniBatchKMeans was fitted without feature names
  warnings.warn(
/home/ubontu/.local/lib/python3.13/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but MiniBatchKMeans was fitted without feature names
  warnings.warn(

In [28]:
df

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek,trip_distance,manhattan_distance,pickup_cluster,dropoff_cluster
0,-73.982155,40.767937,-73.964630,40.765602,455,14,3,17,24,0,1.498521,2.020292,15,11
1,-73.980415,40.738564,-73.999481,40.731152,663,12,6,0,43,6,1.805507,2.347470,17,18
2,-73.979027,40.763939,-74.005333,40.710087,2124,19,1,11,35,1,6.385098,4.577756,15,0
3,-74.010040,40.719971,-74.012268,40.706718,429,6,4,19,32,2,1.485498,0.653645,0,0
4,-73.973053,40.793209,-73.972923,40.782520,435,26,3,13,30,5,1.188588,0.342565,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458639,-73.982201,40.745522,-73.994911,40.740170,778,8,4,13,31,4,1.225080,1.577565,17,6
1458640,-74.000946,40.747379,-73.970184,40.796547,655,10,1,7,35,6,6.049836,4.927422,6,1
1458641,-73.959129,40.768799,-74.004433,40.707371,764,22,4,6,57,4,7.824606,6.924923,16,0
1458642,-73.982079,40.749062,-73.974632,40.757107,373,5,1,15,56,1,1.092564,1.074840,3,3
1458643,-73.979538,40.781750,-73.972809,40.790585,198,5,4,14,44,1,1.134042,1.019365,15,1

In [29]:
trip = df["trip_duration"]                
df = df.drop(columns=["trip_duration"])
trip = np.log1p(trip)

In [30]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train , y_test = train_test_split(df,trip,test_size=.2,random_state=2)

In [31]:
x_train["pickup_hour_sin"] = np.sin(2*np.pi*x_train["pickup_hour"].astype(float)/24)
x_train["pickup_hour_cos"] = np.cos(2*np.pi*x_train["pickup_hour"].astype(float)/24)

x_train["pickup_minute_sin"] = np.sin(2*np.pi*x_train["pickup_minute"].astype(float)/60)
x_train["pickup_minute_cos"] = np.cos(2*np.pi*x_train["pickup_minute"].astype(float)/60)

In [32]:
x_test["pickup_hour_sin"] = np.sin(2*np.pi*x_test["pickup_hour"].astype(float)/24)
x_test["pickup_hour_cos"] = np.cos(2*np.pi*x_test["pickup_hour"].astype(float)/24)

x_test["pickup_minute_sin"] = np.sin(2*np.pi*x_test["pickup_minute"].astype(float)/60)
x_test["pickup_minute_cos"] = np.cos(2*np.pi*x_test["pickup_minute"].astype(float)/60)

In [33]:
x_test.head()

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,pickup_date,pickup_month,pickup_hour,pickup_minute,pickup_dayofweek,trip_distance,manhattan_distance,pickup_cluster,dropoff_cluster,pickup_hour_sin,pickup_hour_cos,pickup_minute_sin,pickup_minute_cos
498569,-73.975594,40.745258,-73.984772,40.752659,23,5,9,0,0,1.129130,1.247724,3,8,0.707107,-7.071068e-01,0.000000,1.000000
1262220,-73.979782,40.775997,-73.963623,40.776051,5,2,17,8,4,1.360677,1.798444,15,16,-0.965926,-2.588190e-01,0.743145,0.669131
268179,-73.989059,40.760288,-73.975189,40.752773,28,2,21,11,6,1.436364,1.772783,8,3,-0.707107,7.071068e-01,0.913545,0.406737
331660,-73.982155,40.774792,-74.013420,40.702259,10,1,18,1,6,8.484530,5.702040,15,0,-1.000000,-1.836970e-16,0.104528,0.994522
280252,-73.980583,40.734035,-73.952606,40.772480,20,2,9,24,5,4.881367,4.290596,17,16,0.707107,-7.071068e-01,0.587785,-0.809017

In [34]:
y_test.head()

498569     6.813445
1262220    5.942799
268179     6.383507
331660     7.412160
280252     6.398595
Name: trip_duration, dtype: float64

In [35]:
x_train = x_train.drop(columns=["pickup_hour","pickup_minute"])
x_test = x_test.drop(columns=["pickup_hour","pickup_minute"])

In [36]:
x_train

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,pickup_date,pickup_month,pickup_dayofweek,trip_distance,manhattan_distance,pickup_cluster,dropoff_cluster,pickup_hour_sin,pickup_hour_cos,pickup_minute_sin,pickup_minute_cos
154556,-73.983650,40.746742,-73.990639,40.755974,23,3,2,1.183325,1.060313,17,8,-0.500000,-8.660254e-01,-1.000000,-1.836970e-16
1454905,-73.789558,40.647129,-73.980217,40.757008,24,4,6,20.188898,24.611099,2,3,-0.500000,8.660254e-01,0.866025,5.000000e-01
1287144,-73.983467,40.766068,-73.978714,40.785049,5,4,1,2.148307,1.110894,15,1,-0.707107,7.071068e-01,-0.809017,-5.877853e-01
739502,-73.870979,40.773750,-73.909691,40.776924,1,1,4,3.278765,4.402568,4,10,-1.000000,-1.836970e-16,0.913545,-4.067366e-01
6879,-73.975403,40.647846,-73.955048,40.733715,22,5,6,9.701188,4.899172,9,12,-0.500000,8.660254e-01,0.978148,2.079117e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1134416,-74.006531,40.744251,-73.991890,40.744141,5,4,1,1.233472,1.631373,6,17,0.707107,7.071068e-01,-0.951057,3.090170e-01
989642,-73.981567,40.771778,-73.790390,40.643879,4,6,5,21.492655,25.182393,15,2,-0.965926,2.588190e-01,0.500000,8.660254e-01
1165799,-73.991676,40.722542,-74.004143,40.707420,23,4,5,1.982715,1.849903,19,0,0.258819,-9.659258e-01,-0.406737,9.135455e-01
209187,-73.953384,40.782204,-73.979568,40.760406,2,3,2,3.276644,3.581505,5,3,0.965926,-2.588190e-01,-0.104528,9.945219e-01
103840,-73.962700,40.762741,-74.011650,40.703133,21,1,3,7.806659,7.274129,11,0,0.707107,-7.071068e-01,0.994522,-1.045285e-01

In [37]:
# from sklearn.ensemble import RandomForestRegressor
# modell = RandomForestRegressor(n_estimators=100, max_depth=20, random_state=42,n_jobs=-1)
# modell.fit(x_train,y_train)

In [38]:
from xgboost import XGBRegressor  # Random Forest এর বদলে XGBoost
model = XGBRegressor(n_estimators=300, learning_rate=0.1, max_depth=8, random_state=42, n_jobs=-1,device="cuda")
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [39]:
y_pred_xg = model.predict(x_test)
# y_pred = modell.predict(x_test)
# y_pred = np.expm1(y_pred)
y_test = np.expm1(y_test)
from sklearn.metrics import r2_score
# r2_score(y_test,y_pred)

/home/ubontu/.local/lib/python3.13/site-packages/xgboost/core.py:751: UserWarning: [23:01:52] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

In [40]:
y_pred_xg = np.expm1(y_pred_xg)
r2_score(y_test,y_pred_xg)

0.8388326346105998

In [41]:
# joblib.dump(model, "uber_model.pkl")